spring.application.name=officespaces-backend
spring.main.allow-bean-definition-overriding=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

spring.jpa.show-sql=true

security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}

server.address=0.0.0.0

app.upload.dir=${UPLOAD_DIR}

spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/
spring.web.resources.chain.cache=false

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

booking.payment.hold-minutes=15

spring.jpa.hibernate.ddl-auto=update